version: '2.1'

services:
  backend:
    image: backend:latest
    build:
      context: ./springboot
      dockerfile: Dockerfile
    expose:
      - "5000"

  frontend:
    image: frontend:latest
    build:
      context: ./react
      dockerfile: Dockerfile
    expose:
      - "3000"
