version: "3.8"

services:
    nginx:
        image: nginx:latest
        network_mode: host
        build:
            context: .
            dockerfile: Dockerfile
        container_name: inmind-nginx
