version: '2.1'

services:
  backend:
    image: backend:latest
    build:
      context: ./springboot
      dockerfile: Dockerfile

  frontend:
    image: frontend:latest
    build:
      context: ./react
      dockerfile: Dockerfile
