version: "3.7"

services:
  app:
    build:
      context: ./BE
      dockerfile: Dockerfile
    expose:
      - "6666"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  app:
    build:
      context: ./FE
      dockerfile: Dockerfile
    expose:
      - "3000"
